/*
 * StreamPunk TypeScript Type Mappings
 * Generated by stream-punk-ts-gen v0.1.0
 * 
 * Basic Type Mappings:
 * - u8, u16, u32, i8, i16, i32, f32, f64 -> number
 * - u64, i64 -> bigint
 * - ch, chw, ch8, ch16, ch32, std::string, std::wstring -> string
 * - bl, bool -> boolean
 */

// Generated interface for AllBasicTypes
export interface AllBasicTypes {
  b: boolean;
  c: string;
  wc: string;
  c8: string;
  c16: string;
  c32: string;
  // TODO: i8: int8_t (not implemented yet)
  // TODO: u8: uint8_t (not implemented yet)
  // TODO: i16: int16_t (not implemented yet)
  // TODO: u16: uint16_t (not implemented yet)
  // TODO: i32: int32_t (not implemented yet)
  // TODO: u32: uint32_t (not implemented yet)
  // TODO: i64: int64_t (not implemented yet)
  // TODO: u64: uint64_t (not implemented yet)
  f: number;
  d: number;
  s: string;
  ws: string;
}

// Basic serialization for AllBasicTypes (basic types only)
export function serializeAllBasicTypesBasic(obj: AllBasicTypes): ArrayBuffer {
  // TODO: Implement basic type serialization
  // This is a placeholder for the first implementation step
  throw new Error('Serialization not implemented yet');
}

// Basic deserialization for AllBasicTypes (basic types only)
export function deserializeAllBasicTypesBasic(buffer: ArrayBuffer): AllBasicTypes {
  // TODO: Implement basic type deserialization
  // This is a placeholder for the first implementation step
  throw new Error('Deserialization not implemented yet');
}

